### ISSUE TITLE
What is the process of reviewing changes?

### ISSUE THREAD

**Issue by yuvalshaia** [ofiwg/ibacm#2]
I have several suggestion and fix for ibacm.
What would be the place to have code review?
Reading thee following thread it seems that this question stays open:
http://www.spinics.net/lists/linux-rdma/msg34162.html

Yuval

**Comment by shefty** [comment]
You can post any patches for review as a PR against this repo.  If you want to copy the linux-rdma mailing list, that would be fine as well.  You can hold discussions in either location.

**Comment by yuvalshaia** [comment]
Thanks
